version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: modern-helpdesk-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - helpdesk-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: modern-helpdesk-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    driver: bridge
